# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6.QtWidgets import *
from qfluentwidgets import FluentIcon as FIF
from qfluentwidgets import *
import sys
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        
        # 将窗口最小大小设置改为固定大小设置
        # 原代码: MainWindow.setMinimumSize(800, 600)
        MainWindow.setFixedSize(800, 600)
        
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 创建主布局管理器
        self.mainLayout = QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(30, 30, 30, 30)  # 设置外边距
        self.mainLayout.setSpacing(20)  # 设置部件间距
        
        # 创建顶部标签区域
        self.topLayout = QVBoxLayout()
        self.topLayout.setSpacing(10)
        
        # 添加标签
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font-size:20px")
        self.label.setObjectName("label")
        self.topLayout.addWidget(self.label)
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.topLayout.addWidget(self.label_2)
        
        # 将顶部布局添加到主布局
        self.mainLayout.addLayout(self.topLayout)
        
        # 创建按钮区域 - 现在不包含killButton
        self.buttonLayout = QVBoxLayout()
        self.buttonLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        
        # 直接创建killButton但不添加到布局中，而是设置固定位置
        self.killButton = PrimaryPushButton(self.centralwidget)
        self.killButton.setGeometry(QtCore.QRect(30, 140, 101, 41))  # 设置固定位置和大小
        self.killButton.setObjectName("killButton")
        self.searchbutton = PushButton(self.centralwidget)
        self.searchbutton.setGeometry(QtCore.QRect(140, 140, 220, 41))  # 设置固定位置和大小
        self.searchbutton.setObjectName("searchbutton")
        self.stopButton = PushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(380, 140, 100, 41))
        self.stopButton.setObjectName("stopButton")
        self.disconnectButton = PushButton(self.centralwidget)
        self.disconnectButton.setGeometry(QtCore.QRect(490, 140, 150, 41))
        self.disconnectButton.setObjectName("disconnectButton")
        self.tishitext = QtWidgets.QLabel(self.centralwidget)
        self.tishitext.setObjectName("tishitext")
        self.tishitext.setGeometry(QtCore.QRect(30, 100, 220, 41))
        self.launchertext = QtWidgets.QLabel(self.centralwidget)
        self.launchertext.setObjectName("launchertext")
        self.launchertext.setGeometry(QtCore.QRect(30, 180, 220, 41))
        self.adminpowershelllaunchbutton = PushButton(self.centralwidget)
        self.adminpowershelllaunchbutton.setGeometry(QtCore.QRect(30,220, 220, 41))
        self.adminpowershelllaunchbutton.setObjectName("adminpowershelllaunchbutton")
        
        # 添加伸缩项，将下方按钮推到底部
        self.mainLayout.addLayout(self.buttonLayout)
        self.mainLayout.addStretch()  # 添加伸缩空间
        
        # 创建底部按钮区域
        self.bottomLayout = QHBoxLayout()
        self.bottomLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        
        # 添加底部按钮
        self.aboutButton = PushButton(self.centralwidget)
        self.aboutButton.setMinimumHeight(40)
        self.aboutButton.setObjectName("aboutButton")
        self.bottomLayout.addWidget(self.aboutButton, 1)

        self.mainLayout.addLayout(self.bottomLayout)
        self.linkbutton = PushButton(self.centralwidget)
        self.linkbutton.setMinimumHeight(40)
        self.linkbutton.setObjectName("linkbutton")
        self.bottomLayout.addWidget(self.linkbutton, 1)
        self.githubbutton = PushButton(self.centralwidget)
        self.githubbutton.setMinimumHeight(40)
        self.githubbutton.setObjectName("githubbutton")
        self.mainLayout.addLayout(self.bottomLayout)
        self.bottomLayout.addWidget(self.githubbutton, 1)
        
        # 设置中心部件的布局
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " 极域杀手"))
        self.label.setText(_translate("MainWindow", "JiyuKiller"))
        self.label_2.setText(_translate("MainWindow", "极域杀手 1.0"))
        self.killButton.setText(_translate("MainWindow", "干掉极域"))
        self.aboutButton.setText(_translate("MainWindow", "关于"))
        self.searchbutton.setText(_translate("MainWindow", "搜索计算机中已有的极域进程"))
        self.tishitext.setText(_translate("MainWindow","主要功能"))
        self.launchertext.setText(_translate('MainWindow','启动台'))
        self.stopButton.setText(_translate("MainWindow","终止极域"))
        self.linkbutton.setText(_translate("MainWindow","打开官网"))
        self.githubbutton.setText(_translate("MainWindow",'Github'))
        self.disconnectButton.setText(_translate("MainWindow","断开与教师机的链接"))
        self.adminpowershelllaunchbutton.setText(_translate("MainWindow","以管理员身份启动powershell"))





if __name__ == "__main__":
    # 测试搜索功能
    # 搜索studentmain.exe（极域学生端）
    
    
    
    # 启动UI
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())