name: Build ITLT

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the package'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5 pyinstaller
        pip install "PyQt-Fluent-Widgets[full]" -i https://pypi.org/simple

    - name: Set up virtual environment
      run: python -m venv .venv

    - name: Activate virtual environment
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Build package
      run: pyinstaller --windowed main.py -i icon.png --dist dist --onefile itlt-${{ inputs.version }}.zip

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ inputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_path: ./dist/itlt-${{ inputs.version }}.zip
        asset_name: itlt-${{ inputs.version }}.zip
        asset_content_type: application/zip
